### ISSUE TITLE
Bumbag + NextJS SSR not working with 1.0.0-rc0

### ISSUE THREAD

**Issue by agustif** [jxom/bumbag#1]
Hi Jake, first of all thanks for building bumbag, I just found it out and it looks awesome!

I tried the latest release candidate and I can't get SSR to work properly

An example app can be seen here: https://with-bumbag-app.vercel.app/

I think code is availably publicly at https://with-bumbag-app.vercel.app/_src

Let me know iff you need something else, looks like an awesome framework btw

**Comment by jxom** [comment]
Hi! 

Seems that the "Getting Started" docs was missing the `<Head/>` tag in the Next.js example.

Try copy and paste the following into your `_document.js` file, and try again: 

```jsx
import Document, { Head, Main, NextScript } from 'next/document'
import { extractCritical } from 'emotion-server'

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    const styles = extractCritical(initialProps.html)
    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          <style
            data-emotion-css={styles.ids.join(' ')}
            dangerouslySetInnerHTML={{ __html: styles.css }}
          />
        </>
      ),
    }
  }

  render() {
    return (
      <html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

**Comment by agustif** [comment]
Still no SSR, with your version or importing head like this doesn't work either.

`import Document, { Main, NextScript } from 'next/document'
import { extractCritical } from 'emotion-server'
import Head from 'next/head'
export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    const styles = extractCritical(initialProps.html)
    return {
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          <styles
            data-emotion-css={styles.ids.join(' ')}
            dangerouslySetInnerHTML={{ __html: styles.css }}
          />
        </>
      ),
    }
  }

  render() {
    return (
      <html>
      <Head>
        <title>My page title</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}`

**Comment by agustif** [comment]
This is the warning I get about different id's on clieent/serveer



```
dll_f9de5cbc314a1e41f91e.js:340 Warning: Prop `id` did not match. Server: "id-h55sls" Client: "id-qo6dtr"
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by Disclosure.Content)
    in Disclosure.Content
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by PageWithHeader)
    in PageWithHeader (at pages/index.tsx:8)
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by Box)
    in Box (created by Provider)
    in PageProvider (created by Provider)
    in ToastProvider (created by Provider)
    in IdProvider (created by Provider)
    in Provider (created by Provider)
    in ThemeProvider (created by Provider)
    in Provider (at pages/index.tsx:7)
    in MyApp (at _app.tsx:48)
    in div (created by ForwardRef(Box))
    in ForwardRef(Box)
    in Unknown (created by Box)
    in Box (created by Provider)
    in PageProvider (created by Provider)
    in ToastProvider (created by Provider)
    in IdProvider (created by Provider)
    in Provider (created by Provider)
    in ThemeProvider (created by Provider)
    in Provider (at _app.tsx:47)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
printWarning @ dll_f9de5cbc314a1e41f91e.js:340
DevTools failed to load SourceMap: Could not load co
```
