### ISSUE TITLE
Type definition not available

### ISSUE THREAD

**Issue by ericjiang97** [jxom/bumbag#4]
Type definition is not available -  

VSCode Typescript Hint:

> Could not find a declaration file for module 'bumbag'. '[PATH_TO_DIR]/node_modules/bumbag/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/bumbag` if it exists or add a new declaration (.d.ts) file containing `declare module 'bumbag';`ts(7016)

Error:
```
error - ./pages/_app.tsx
Attempted import error: 'Provider' is not exported from 'bumbag' (imported as 'BumbagProvider').
```

**Comment by ericjiang97** [comment]
https://www.github.com/ericjiang97/nextjs-personal/tree/feat%2Fupgrade-to-bumbag/tsconfig.json

**Comment by agustif** [comment]
Hey I got the same error when I wasn't installing the RC explicitly

If you want to try it out, the docs are not updated for the RC

install with:

$ yarn add bumbag@1.0.0-rc.0

or

$ npm install bumbag@1.0.0-rc.0

**Comment by jxom** [comment]
I'll update the latest tag to `rc`..
